chat/urls.py
from django.urls import path

from . import views
app_name="chat"
urlpatterns = [
path('', views.index, name='index'),
path('room/', views.room, name='room'),
]

trading/urls.py
from django.urls import path
from . import views

app_name = 'trading'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(),name='login'),
    path('logoff/', views.Logoff, name='logoff'),
    path('', views.postlogin.as_view(), name='index'),
    path('buy/', views.Buy.as_view(), name='buy'),
    path('sell/', views.Sell.as_view(), name='sell'),
    path('transactions/', views.Transactions.as_view(), name='transactions'),
]

wallstreet_chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('trading.urls')),
    path('chat/',include('chat.urls')),

]

chat/models.py
from django.db import models
from trading.models import *

class Message(models.Model):
    message=models.TextField(max_length=200000,null = True, blank = True, default = "")
    message_time = models.DateTimeField(auto_now_add=True,null=True)
    author=models.ForeignKey(Profile, related_name='message_author', null=True , blank= True, on_delete=models.PROTECT)

    def __str__(self):
        return self.author.user.first_name + ": " + str(self.message)[0:15]

chat/views.py
from django.shortcuts import render

from chat.models import Message


def index(request):
    context = {}
    return render(request, "chat/chat.html", context=context)


def room(request):
    username = request.user.id
    messages=Message.objects.filter(author__user=request.user)
    context = {
        "room_name": str(username),
        "buy_sell": 0,
        "company_name": "default",
        "bidding_price": -1,
        "share_count": -1,
        "messages":messages,
        "username":request.user.username
        
    }
    return render(request, "chat/room.html", context=context)

chat/templates/chat/chat.html
<!-- app/templates/app/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/app/' + roomName + '/';
        };
    </script>
</body>
</html> -->
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
</head>
<body>

<h2>Chat Messages</h2>

<div class="container">
  <img src="/w3images/bandmember.jpg" alt="Avatar" style="width:100%;">
  <p>Hello. How are you today?</p>
  <span class="time-right">11:00</span>
</div>

<div class="container darker">
  <img src="/w3images/avatar_g2.jpg" alt="Avatar" class="right" style="width:100%;">
  <p>Hey! I'm fine. Thanks for asking!</p>
  <span class="time-left">11:01</span>
</div>

<div class="container">
  <img src="/w3images/bandmember.jpg" alt="Avatar" style="width:100%;">
  <p>Sweet! So, what do you wanna do today?</p>
  <span class="time-right">11:02</span>
</div>

<div class="container darker">
  <img src="/w3images/avatar_g2.jpg" alt="Avatar" class="right" style="width:100%;">
  <p>Nah, I dunno. Play soccer.. or learn more coding perhaps?</p>
  <span class="time-left">11:05</span>
</div>

</body>
</html>

chat/templates/chat/room.html
{%load static%}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chatroom</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="all,follow">
        <!-- Bootstrap CSS-->
        <link rel="stylesheet" href="{% static 'trading/vendor/bootstrap/css/bootstrap.min.css'%}">
        <!-- Font Awesome CSS-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <!-- Google fonts - Popppins for copy-->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,800">
        <!-- orion icons-->
        <link rel="stylesheet" href="{% static 'trading/css/orionicons.css'%}">
        <!-- theme stylesheet-->
        <link rel="stylesheet" href="{% static 'trading/css/style.default.css'%}" id="theme-stylesheet">
        <!-- Custom stylesheet - for your changes-->
        <link rel="stylesheet" href="{% static 'trading/css/custom.css'%}">
        <!-- Favicon-->
        <link rel="shortcut icon" href="{% static 'trading/img/favicon.png'%}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">


    <style type="text/css">
        #loading {
            width: 100%;
            height: 100vh;
            background: #000;
        }
        
        .page-holder {
            background: url('{% static 'trading/img/1.png'%}');
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        body {
  font-family: sans-serif !important;
}


.heading {
  color: #fff;
  margin: 30px;
  font-weight: 600;
}

img {max-width: 100%;}
		.inbox_msg {
		  border: 1px solid #c4c4c4;
		  clear: both;
		  overflow: hidden;
		}
		.top_spac{ margin: 20px 0 0;}


		.recent_heading {float: left; width:40%;}

		.headind_srch{ padding:10px 29px 10px 20px; overflow:hidden; border-bottom:1px solid #c4c4c4;}

		.recent_heading h4 {
		  color: #05728f;
		  font-size: 21px;
		  margin: auto;
		}

		.chat_ib h5{ font-size:15px; color:#464646; margin:0 0 8px 0;}
		.chat_ib h5 span{ font-size:13px; float:right;}
		.chat_ib p{ font-size:14px; color:#989898; margin:auto}
		.chat_img {
		  float: left;
		  width: 11%;
		}
		.chat_ib {
		  float: left;
		  padding: 0 0 0 15px;
		  width: 88%;
		}

		.chat_people{ overflow:hidden; clear:both;}
		.chat_list {
		  border-bottom: 1px solid #c4c4c4;
		  margin: 0;
		  padding: 18px 16px 10px;
		}
		.inbox_chat { height: 550px; overflow-y: scroll;}

		.active_chat{ background:#ebebeb;}

		.incoming_msg_img {
		  display: inline-block;
		  width: 6%;
		}
		.received_msg {
		  display: inline-block;
		  padding: 0 0 0 10px;
		  vertical-align: top;
		  width: 92%;
		 }
		 .received_withd_msg p {
		  background: #e4e8fb none repeat scroll 0 0;
		  border-radius: 3px;
		  color: #646464;
		  font-size: 14px;
		  margin: 0;
		  padding: 5px 10px 5px 12px;
		  width: 100%;
		}
		.time_date {
		  color: #747474;
		  display: block;
		  font-size: 10px;
		  margin: 3px 0 0;
		}
		.received_withd_msg { width: 70%;}
		.mesgs {
		  float: left;
		  padding: 40px;
		}

		 .sent_msg p {
		  background: #3F51B5 none repeat scroll 0 0;
		  border-radius: 3px;
		  font-size: 14px;
		  margin: 0; color:#fff;
		  padding: 5px 10px 5px 12px;
		  width:100%;
		}
		.outgoing_msg{ overflow:hidden; margin:26px 0 26px;}
		.sent_msg {
      float: right;
		  width: 70%;
      text-align: right;
		}
		.input_msg_write input {
		  background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
		  border: medium none;
		  color: #4c4c4c;
		  font-size: 15px;
		  min-height: 48px;
		  width: 100%;
		}

		.type_msg {border-top: 1px solid #c4c4c4;position: relative;}
		.msg_send_btn {
		  background: #05728f none repeat scroll 0 0;
		  border: medium none;
		  border-radius: 50%;
		  color: #fff;
		  cursor: pointer;
		  font-size: 17px;
		  height: 33px;
		  position: absolute;
		  right: 0;
		  top: 11px;
		  width: 33px;
		}
		.messaging { background: #fff;}
		.msg_history {
		  max-height: 516px;
		  overflow-y: auto;
		}

.credit {
  margin-bottom: 20px;
  margin-top: 20px;
}


.credit a {
  color: #fff;
  font-weight: 300;
  letter-spacing: 2px;
  border-bottom: dotted 1px;
}
    </style>
</head>
<body onload="start()">
    <div id="loading"></div>
    <!-- navbar-->
    <header class="header">
        <nav class="navbar sticky-top navbar-expand-lg px-4 py-2 bg-white shadow">
        <a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead">
        <i class="fas fa-align-left"></i></a>
        <a href="#" class="navbar-brand font-weight-bold text-uppercase text-base">Wallstreet</a>
            <ul class="ml-auto d-flex align-items-center list-unstyled mb-0">

                
                <li class="nav-item dropdown ml-auto">
                    <a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'trading/img/navLogo.png' %}" alt="Jason Doe" style="max-width: 1.5rem;" class="img-fluid rounded-circle shadow"></a>
                    <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">{{ profile.user.username }}</strong><small>Cash: {{ profile.cash }}</small><br/><small>Net Worth: {{ profile.netWorth }}</small></a>
                        <div class="dropdown-divider"></div><a href="../#sectionMyShares" class="dropdown-item">Your Shares</a>
                        <div class="dropdown-divider"></div><a href="{% url 'trading:transactions' %}" class="dropdown-item">Transaction History</a>
                        <div class="dropdown-divider"></div><a href="{%url 'trading:logoff'%}" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>

    
    <div class="d-flex align-items-stretch">
        <div id="sidebar" class="sidebar py-3">
            <ul class="sidebar-menu list-unstyled" style="margin-left:-15px;">
                <li class="sidebar-list-item"><a href="{%url 'trading:index' %}" class="sidebar-link text-muted"><i class="o-home-1 mr-3 text-gray"></i><span>Home</span></a></li>
                <li class="sidebar-list-item"><a href="../#sectionMyShares" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>Your Shares</span></a></li>
                <li class="sidebar-list-item"><a href="{%url 'trading:buy' %}" class="sidebar-link text-muted "><i class="o-sales-up-1 mr-3 text-gray"></i><span>Buy</span></a></li>
                
                <li class="sidebar-list-item"><a href="{%url 'trading:sell' %}" class="sidebar-link text-muted"><i class="o-sales-up-1 mr-3 text-gray"></i><span>Sell</span></a></li>
                <li class="sidebar-list-item">
                    <a href="{% url 'chat:room' %}" class="sidebar-link text-muted active"
                      ><i class="far fa-comment mr-3 text-gray"></i><span>Chat</span></a
                    >
                  </li>
                <li class="sidebar-list-item"><a href="{%url 'trading:transactions' %}" class="sidebar-link text-muted"><i class="o-table-content-1 mr-3 text-gray"></i><span>Transactions</span></a></li>

                <li class="sidebar-list-item"><a href="{%url 'trading:logoff'%}" class="sidebar-link text-muted"><i class="o-exit-1 mr-3 text-gray"></i><span>Logout</span></a></li>
            </ul>

        </div>

        

        <div class="page-holder w-100 d-flex flex-wrap">
            <!-- <div class="container-fluid px-xl-5">
                <section class="py-5">

                    <div class="row d-flex justify-content-center align-items-center">

                        
                                <textarea id="chat-log" cols="100" style="width:62%;"rows="20"></textarea><br>
    <input id="chat-message-input" type="text" style="width: 55%; padding: 5px;" placeholder="Enter your message here " size="100"><br>
    <input id="chat-message-submit" type="button" style="background-color: rgb(60, 196, 100); height: 40px; width:80px;" value="Send">
                                </div>
                </section>
            </div> -->
            
        <section class="section">
            <div class="container">
                <div class="columns is-multiline">
                    <div class="column is-6 is-offset-3 mb-6">
                        <section class="hero is-primary">
                            <div class="hero-body">
                                <p class="title">
                                    Broker Chat
                                </p>
                                <p class="subtitle">
                                    
                                </p>
                            </div>
                        </section>
                    </div>

                    <div class="column is-6 is-offset-3">
                        <div class="box">
                            <div id="chat-messages" style="max-height: 300px; overflow-y: scroll;">{% for m in messages %}<b>{{ m.author.user.first_name }}</b>: {{ m.message }}<br>{% endfor %}</div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <input class="input" type="text" placeholder="Message" id="chat-message-input">
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <a class="button is-info" id="chat-message-submit">Submit</a>
                            </div>
                        </div>

                        <small class="has-text-grey-light">Your username: {{ username }}</small>
                    </div>
                </div>
            </div>
        </section>
    {{ room_name|json_script:"room-name" }}
    {{ buy_sell|json_script:"buy_sell" }}
    {{ company_name|json_script:"company_name" }}
    {{ bidding_price|json_script:"bidding_price" }}
    {{ share_count|json_script:"share_count" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        var buy_sell = JSON.parse(document.getElementById('buy_sell').textContent);
        var company_name = JSON.parse(document.getElementById('company_name').textContent);
        var bidding_price = JSON.parse(document.getElementById('bidding_price').textContent);
        var share_count = JSON.parse(document.getElementById('share_count').textContent);


        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/app/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            buy_sell=data.buy_sell
            company_name=data.company_name
            bidding_price=data.bidding_price
            share_count=data.share_count

            if (data.message) {
                document.querySelector('#chat-messages').innerHTML += ('</b>: ' + data.message + '<br>');
                document.querySelector('#chat-messages').innerHTML += ('</b>: ' + data.message1 + '<br>');

            } else {
                alert('The message is empty!');
            }

            scrollToBottom();
                
            document.querySelector('#chat-log').value += (data.message + '\n');
            document.querySelector('#chat-log').value += (data.message1 + '\n');

        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'buy_sell':buy_sell,
                'company_name':company_name,
                'bidding_price':bidding_price,
                'share_count':share_count,
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>